energywebfoundation/iam-client-lib

- bili.config.ts
Fixes #47 
Update bili's config to bundle up the `nats.ws` library
> [MYEN-427] update bili config to resolve nodejs issue

- bili.config.ts
Just added some additional comments based on our chat in the original PR for the bili config changes. I think it could be helpful when we're coming back to it in the future.
> Additional comments to explain changes to bili config

- src/utils/isBrowser.ts
- test/utils/isBrowser.test.ts
I think the logic of `isBrowser` might have been backwards. I added some tests and fixed. Let me know if this makes sense
> Fixing isBrowser logic and adding tests

- examples/angular-dapp/package-lock.json
- examples/angular-dapp/package.json
- examples/react-dapp/package-lock.json
- examples/react-dapp/package.json
- examples/vue-dapp/package-lock.json
- examples/vue-dapp/package.json
- package-lock.json
- package.json
See https://www.npmjs.com/package/axios/v/0.20.0
Was notified by Kiran on devops team who apparently got a dependabot alert. Did anyone else get it?
> Updating axios to 0.21.1 to fix SSRF security vulnerability

- src/iam.ts
- src/iam/iam-base.ts
- src/utils/isBrowser.ts
- test/utils/isBrowser.test.ts
Reverts energywebfoundation/iam-client-lib#77 
I found major issues testing the `isBrowser` fix again locally. My initial testing was incorrect.
> Revert "Fixing isBrowser logic and adding tests"

- src/iam.ts
- src/iam/iam-base.ts
Before merging [this iam-cache-server PR](https://github.com/energywebfoundation/iam-cache-server/pull/58) needs to be merged
> fix: update logic for changing ownership and deleting

- package.json
- src/cacheServerClient/cacheServerClient.ts
- src/errors/CacheClientNotProvided.ts
- src/errors/ENSRegistryNotInitializedError.ts
- src/errors/ENSResolverNotInitializedError.ts
- src/errors/ENSTypeNOtSupportedError.ts
- src/errors/ErrorMessages.ts
- src/errors/NatsConnectionNotEstablishedError.ts
- src/errors/index.ts
- src/iam-client-lib.ts
- src/iam.ts
- src/iam/iam-base.ts
- src/signer/Signer.ts
- src/signer/SignerFactory.ts
- test/initializeConnection.testSuite.ts
> [MYEN-373] add login in to cache server

- docs/api/README.md
- docs/api/classes/cacheserverclient.md
- docs/api/classes/changeownershipnotpossibleerror.md
- docs/api/classes/deletingnamespacenotpossibleerror.md
- docs/api/classes/gnosisiam.md
- docs/api/classes/iambase.md
- docs/api/classes/owner.md
- docs/api/classes/signerfactory.md
- docs/api/enums/error_messages.md
- docs/api/enums/walletprovider.md
- docs/api/globals.md
- docs/api/interfaces/claim.md
- docs/api/interfaces/claimdata.md
- docs/api/interfaces/iapp.md
- docs/api/interfaces/icacheserverclient.md
- docs/api/interfaces/iclaimissuance.md
- docs/api/interfaces/iclaimrejection.md
- docs/api/interfaces/iclaimrequest.md
- docs/api/interfaces/imessage.md
- docs/api/interfaces/iorganization.md
- docs/api/interfaces/irole.md
- docs/api/interfaces/iroledefinition.md
- package-lock.json
- package.json
downgrade typedoc-plugin-markdown as getting error from `build:api_docs`. Downgrade fixes issue.
Error:
```
/Users/john/ew/iam-client-lib/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:54
if (this instanceof types_1.LiteralType) {
^
TypeError: Right-hand side of 'instanceof' is not an object
at StringLiteralType.type (/Users/john/ew/iam-client-lib/node_modules/typedoc-plugin-markdown/dist/resources/helpers/type.js:54:14)
at getType (/Users/john/ew/iam-client-lib/node_modules/typedoc-plugin-markdown/dist/resources/helpers/declaration-title.js:30:24)
at DeclarationReflection.declarationTitle (/Users/john/ew/iam-client-lib/node_modules/typedoc-plugin-markdown/dist/resources/helpers/declaration-title.js:22:124)
at DeclarationReflection.wrapper …
```
> chore(docs): update docs for v2.0

- README.md
- src/iam-client-lib.ts
- src/iam/chainConfig.ts
- src/iam/iam-base.ts
- src/utils/constants.ts
In this PR I've added messaging option configurable same as chain and cacheServer. I've also updated readme, to new changes.
> feat(messaging): make messaging options chain agnostic

- src/iam.ts
Sorry for the formatting changes mixed in 😅
> fix(verifyEnrolmentPreconditions): check conditions length

- src/iam.ts
- test/assets.testsuite.ts
First draft of implementing asset agent delegation - updating asset did document.
> [SWTCH-276] implement asset agent delegation

- src/cacheServerClient/cacheServerClient.ts
https://energyweb.atlassian.net/browse/SWTCH-841
Should be merged after https://github.com/energywebfoundation/iam-cache-server/pull/121
> bug/inconsistent claim query flags names 

- package-lock.json
- package.json
- src/cacheServerClient/cacheServerClient.types.ts
- src/errors/ErrorMessages.ts
- src/iam.ts
- src/iam/chainConfig.ts
- src/iam/iam-base.ts
- test/claims.testSuite.ts
- test/iam.test.ts
- test/setup_contracts.ts
To distinguish between off-chain and on-chain way of role registration added `RegistrationTypes` enum.
On-chain registration differs from off-chain in:
- agreement claim must be published
`claimTypeVersion` is required in enrollment request, because it is required by on-chain registration
? Verification of enrollment preconditions requires at least one role
> feature/SWTCH-905 request on-chain role

- .travis.yml
- README.md
> Fix: Updates documentation to state DID document prerequisite requirement

- package-lock.json
- package.json
- src/iam/chainConfig.ts
should be merged after https://github.com/energywebfoundation/iam-cache-server/pull/144
> bug/SWTCH-1089 owner can't enroll his asset

- .github/workflows/deploy.yml
set npm token /home/runner/.npmrc
> set npm token /home/runner/.npmrc

- .github/workflows/deploy.yml
- semantic release via codfish action
> use codfish semantic release

- bili.config.ts
- src/iam.ts
- src/iam/iam-base.ts
- test/claimsTests/enrollmentClaimsTests.ts
- test/testUtils/mocks.ts
changed the way nats.ws is referenced according to document https://github.com/nats-io/nats.ws/blob/master/developer_notes.md
> fix(nats): change in the way nats is referenced

- docs/api/classes/cacheServerClient_cacheServerClient.CacheServerClient.md
- docs/api/interfaces/cacheServerClient_ICacheServerClient.ICacheServerClient.md
- docs/api/modules/cacheServerClient_cacheServerClient_types.md
- src/cacheServerClient/ICacheServerClient.ts
- src/cacheServerClient/cacheServerClient.ts
- src/cacheServerClient/cacheServerClient.types.ts
fix to parentNamespace field and enforce type safety in interface implementation
> bug/ICL-104 fix(core): update cache server interface to latest version and secure types 

- package-lock.json
- package.json
- src/iam.ts
- test/claimsTests/createIdentityTests.ts
> fix(createDelegateProof): set issuer identity

- docs/api/classes/GnosisIam.GnosisIam-1.md
- docs/api/classes/iam.IAM.md
- docs/guides/asset.md
- src/iam.ts
> Add Asset Guide and API markdown

- jest.config.js
- package.json
path to env parameters got fixed
> fix(jest): make work of the npm test:watch and test:watch:windows

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- e2e/claims.service.e2e.ts
- e2e/domains.service.e2e.ts
- e2e/staking.pool.e2e.ts
- e2e/staking.service.e2e.ts
- e2e/utils/setup_contracts.ts
- package-lock.json
- package.json
- src/modules/claims/claims.service.ts
add issuer fields in role definition and claims in new modularised iam-client-lib
> feat(claims) ICL-135 add issuer fields in role definition and claims

- docs/api/classes/modules_cacheClient_cacheClient_service.CacheClient.md
- docs/api/interfaces/modules_cacheClient_ICacheClient.ICacheClient.md
- src/modules/cacheClient/ICacheClient.ts
- src/modules/cacheClient/cacheClient.service.ts
Authentication tests can be added after verification coded is consolidated in ew-did-registry
> bug/ICL-145 Forbidden access to assets endpoints

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/interfaces/modules_didRegistry_did_types.ClaimData.md
- src/modules/claims/claims.service.ts
- src/modules/didRegistry/did.types.ts
publishPublicClaim Claim Data issuerFields typo fix
> fix(issuerFields): fix to issuerFields on publishPublicClaim

- docs/api/classes/modules_didRegistry_didRegistry_service.DidRegistry.md
- src/modules/didRegistry/didRegistry.service.ts
Remove automatic creation of the DID document upon initialization. Instead, create a method that will allow create it when needed.
> feat(DID): remove did document creation upon initialization

- docs/api/classes/modules_cacheClient_cacheClient_service.CacheClient.md
- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/interfaces/modules_cacheClient_ICacheClient.ICacheClient.md
- src/modules/cacheClient/ICacheClient.ts
- src/modules/cacheClient/cacheClient.service.ts
- src/modules/claims/claims.service.ts
getClaimById method for single claim retrieval
> feat(claims): new getClaimById method

- .github/workflows/deploy.yml
Reverts energywebfoundation/iam-client-lib#349
Original PR was unintentional
> Revert "bug/ICL-156_failed dependabot PR's"

- docs/api/enums/modules_assets_assets_types.AssetHistoryEventType.md
- docs/api/enums/modules_claims_claims_types.ClaimEventType.md
- docs/api/modules/index.md
- docs/api/modules/modules_claims.md
- docs/api/modules/modules_claims_claims_types.md
- src/modules/assets/assets.types.ts
- src/modules/claims/claims.types.ts
- src/modules/messaging/messaging.service.ts
- event types lower case as in cache server
- claim event types for SB to handle events without typos
- new message pattern '<' instead of '*' that catches events of any number of parts separated by dots
> feat(nats): event types and new catch-all message pattern

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/modules/modules_claims_claims_types.md
- e2e/claims.service.e2e.ts
- package-lock.json
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
PR is work-in-progress. Still need to add tests, for example.
> Adding option to not pulish onchain when issuing

- docs/api/classes/modules_staking_staking_pool_service.StakingPoolService.md
- src/modules/staking/staking-pool.service.ts
Method for getting stake ratio.
> feat: add method for getting ratio from staking pool.

- docs/api/interfaces/modules_claims_claims_types.IClaimRequest.md
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
claimType and claimTypeVersion added to claim request
> fix(claims): enrich claim request with type and version

- src/modules/messaging/messaging.service.ts
http protocol to ws, https protocol to wss
> fix(nats): fix http to ws replacement

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/modules/modules_claims_claims_types.md
- src/modules/messaging/messaging.service.ts
<. sign did not capture all possible events. *.*. seems to work accurately.
> fix(nats): changed subject mask to ensure capturing all events for did

- src/modules/cacheClient/cacheClient.service.ts
PR to resolve auth issue where token is not updated when logging in as a different user.
No time to do the below:
> Revert "bug/ICS-124 random unauthorized to cache server "

- README.md
- docs/api/README.md
a minor doc fix in order to trigger a release that contains 43c00be8973164255a2fd3d4c0afe8b57660de48
> fix(cacheClient): trigging release of previous commit

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/interfaces/modules_claims_claims_types.IClaimRejection.md
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
rejection reason to give requester more details about the causes
> feat(claims): rejection reason while rejecting the claim

- mkdocs.yml
> add claim guide to guides dropdown

- docs/guides/claim.md
> add overview header

- e2e/claims.service.e2e.ts
fixes https://github.com/energywebfoundation/iam-client-lib/runs/4774745687?check_suite_focus=true
> bug/ enrol and issue test

- docs/CHANGELOG.md
- package.json
* **test:** expect requestorField in claim ([a5fe8af](https://github.com/energywebfoundation/iam-client-lib/commit/a5fe8af7d6769f28aff1d46e73cec1d78031b774))
* disable staking pool initialization ([78c7815](https://github.com/energywebfoundation/iam-client-lib/commit/78c781512df09e5d91f575034856450fe40f6698))
* ensure eth_sign signature ([5b4dec3](https://github.com/energywebfoundation/iam-client-lib/commit/5b4dec39f66dd642936bb0e8ef533f199b0f59f7))
* revert config changes from dev to volta ([adafda4](https://github.com/energywebfoundation/iam-client-lib/commit/adafda4f44ebf4aa6c08f99909c1f5048693ac1c))
* **assets:** rollback asset event type to uppercase ([52359cd](https://github.com/energywebfoundation/iam-client-lib/commit/52359cd01bce95ae778b8ddf345e66880070e839))
* **assets:** …
> chore(release): 4.0.0 [skip ci]

- docs/api/classes/ClaimsService.md
- docs/api/classes/MessagingService.md
- src/modules/claims/claims.service.ts
Replacing the order of role issuing help prevent the error 4001 when logged in using MetaMask.
> fix(claim): fix issuing a claim with on-chain and off-chain request

- docs/api/classes/ClaimsService.md
- docs/api/enums/ERROR_MESSAGES.md
- docs/api/interfaces/Claim.md
- docs/api/interfaces/IClaimIssuance.md
- docs/api/modules.md
- e2e/claims.service.e2e.ts
- src/errors/ErrorMessages.ts
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
there is on chain an off chain erolment possibility with off chain as default one.
> feat(claims): enable on chain enrolment without previous request

- docs/api/interfaces/IApp.md
- docs/api/interfaces/IOrganization.md
- docs/api/interfaces/IRole.md
- src/modules/domains/domains.types.ts
Fix IRole, IOrganization and IApp to match counterparts on ICS.
> fix: fix role, app, org interfaces

- docs/CHANGELOG.md
https://energyweb.atlassian.net/browse/ICL-223
Changes in question https://github.com/energywebfoundation/iam-client-lib/pull/431
> bug/ICL-223 v4.1 breaking changes were not added to changelog

- package-lock.json
- package.json
I forgot to install the most important package :smile:  
https://github.com/energywebfoundation/iam-client-lib/pull/476
> build(deps): install @energyweb/semantic-release-config

- src/config/cache.config.ts
staging is more stable and should be default
> fix(cache.config): default for volta should be staging

- .github/PULL_REQUEST_TEMPLATE.md
My proposal for pull request check list. Let me know what you think and feel free to propose your points.
> chore: add pull request checklist

- e2e/assets.service.e2e.ts
- e2e/cacheClient.e2e.ts
- e2e/claims.service.e2e.ts
- e2e/utils/ERC1056.json
- scripts/change-resolver.ts
- src/init.ts
- src/modules/assets/assets.service.ts
- src/modules/cacheClient/ICacheClient.ts
- src/modules/cacheClient/cacheClient.service.ts
- src/modules/claims/claims.service.ts
- src/modules/didRegistry/didRegistry.service.ts
- src/modules/messaging/messaging.service.ts
- src/modules/signer/ekcSigner.ts
- src/modules/signer/gnosisSigner.ts
- src/modules/signer/metamaskSigner.ts
- src/modules/signer/signer.service.ts
- src/modules/signer/walletConnectKms.ts
- src/modules/signer/walletConnectMetamask.ts
- src/modules/staking/index.ts
- src/modules/staking/staking-pool.service.ts
Apply style rules. I forgot to run `prettier` on all files probably in this PR https://github.com/energywebfoundation/iam-client-lib/pull/467.
> style: apply prettier config

- README.md
- docs/api/README.md
- docs/api/modules.md
- docs/guides/asset.md
- docs/guides/initialization.md
> Docs/icl 213/update asset docs

- docs/api/classes/ClaimsService.md
- e2e/claims.service.e2e.ts
- scripts/patches-build.js
- src/config/logger.config.ts
- src/modules/didRegistry/didRegistry.service.ts
- src/modules/domains/domains.service.ts
- src/modules/messaging/messaging.service.ts
- src/modules/signer/metamaskSigner.ts
- src/modules/signer/signer.service.ts
- src/utils/logger.ts
- src/utils/updateLegacyIssuers.ts
all console logs turned into logger implementing ILogger
functionalities:
- default logger - ConsoleLogger
- ILogger : debug, info, warn, error
- ability to get logger everywhere with getLogger():ILogger
- ability to set custom logger implmenting ILogger with setLogger(ILogger)
- ability to set min logLevel
> feat(core): feat/ICL-114 custom logger

- README.md
> document install in browser application

- docs/api/classes/ClaimsService.md
- docs/api/enums/ERROR_MESSAGES.md
- src/errors/ErrorMessages.ts
- src/modules/claims/claims.service.ts
Fix role publishing for on chain claim
> fix(claim): fix public claim publishing

- docs/api/classes/CacheClient.md
- docs/api/classes/VerifiableCredentialsServiceBase.md
- docs/api/interfaces/Claim.md
- docs/api/interfaces/StoreVcResult.md
- docs/api/interfaces/WebNodeQueryMessage.md
- docs/api/interfaces/WebNodeReply.md
- docs/api/interfaces/WebNodeRequestObject.md
- docs/api/interfaces/WebNodeResponseObject.md
- docs/api/interfaces/WebNodeStatus.md
- docs/api/interfaces/WebNodeWriteMessage.md
- docs/api/modules.md
- e2e/credentials-storage-client.e2e.ts
- e2e/verifiable-credentials.service.e2e.ts
- package-lock.json
- package.json
- src/init.ts
- src/modules/claims/claims.types.ts
- src/modules/verifiable-credentials/storage-client.ts
- src/modules/verifiable-credentials/types/decentralized-web-node.types.ts
- src/modules/verifiable-credentials/types/index.ts
- src/modules/verifiable-credentials/types/storage-client.types.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
> feat(vc): store vc in decentralized-web-node

- docs/guides/claim.md
- docs/guides/organization.md
Update examples object in documentation. Especially replace `OKE.iam.ewc` with `eneryweb.iam.ewc`.
> docs: update examples role objects

- README.md
- docs/api/README.md
> docs(README): fix link to read the docs

- src/modules/claims/claims.service.ts
Fix delegate proof token payload
> fix: fix delegate proof token payload

- docs/api/classes/modules_assets.AssetsService.md
- docs/api/interfaces/modules_assets.AcceptAssetOfferOptions.md
- docs/api/interfaces/modules_assets.AcceptOfferTxOptions.md
- docs/api/interfaces/modules_assets.CancelAssetOfferOptions.md
- docs/api/interfaces/modules_assets.CancelOfferTxOptions.md
- docs/api/interfaces/modules_assets.GetAssetByIdOptions.md
- docs/api/interfaces/modules_assets.GetAssetHistoryOptions.md
- docs/api/interfaces/modules_assets.GetOfferedAssetsOptions.md
- docs/api/interfaces/modules_assets.GetOwnedAssetsOptions.md
- docs/api/interfaces/modules_assets.GetPreviouslyOwnedAssetsOptions.md
- docs/api/interfaces/modules_assets.OfferAssetOptions.md
- docs/api/interfaces/modules_assets.OfferAssetTxOptions.md
- docs/api/interfaces/modules_assets.RejectAssetOfferOptions.md
- docs/api/interfaces/modules_assets.RejectOfferTxOptions.md
- docs/api/modules/modules_assets.md
- src/modules/assets/assets.service.ts
- src/modules/assets/assets.types.ts
- src/modules/did-registry/did-registry.service.ts
- Improve asset service methods documentation
- Add examples to asset service methods
> docs(asset): improve asset service documentation

- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- src/errors/error-messages.ts
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
Subject agreement as optional parameter in claim request issuance interface.
> fix(claim): fix claim service issuance interfaces

- docs/api/classes/modules_domains.DomainsService.md
- docs/api/interfaces/modules_domains.ChangeAppOwnershipOptions.md
- docs/api/interfaces/modules_domains.ChangeOrgOwnershipOptions.md
- docs/api/interfaces/modules_domains.ChangeRoleOwnershipOptions.md
- docs/api/interfaces/modules_domains.CheckExistenceOfDomainOptions.md
- docs/api/interfaces/modules_domains.CreateApplicationOptions.md
- docs/api/interfaces/modules_domains.CreateOrganizationOptions.md
- docs/api/interfaces/modules_domains.CreateRoleOptions.md
- docs/api/interfaces/modules_domains.DeleteApplicationOptions.md
- docs/api/interfaces/modules_domains.DeleteOrganizationOptions.md
- docs/api/interfaces/modules_domains.DeleteRoleOptions.md
- docs/api/interfaces/modules_domains.GetDefinitionOptions.md
- docs/api/interfaces/modules_domains.GetENSTypesByOwnerOptions.md
- docs/api/interfaces/modules_domains.GetRolesByNamespaceOptions.md
- docs/api/interfaces/modules_domains.GetSubdomainsOptions.md
- docs/api/interfaces/modules_domains.IsOwnerOptions.md
- docs/api/interfaces/modules_domains.ReturnStep.md
- docs/api/interfaces/modules_domains.ReturnStepWithRetryCheck.md
- docs/api/interfaces/modules_domains.SetRoleDefinitionOptions.md
- docs/api/interfaces/modules_domains.ValidateOwnershipOptions.md
- docs/api/modules/modules_domains.md
- src/modules/domains/domains.service.ts
- src/modules/domains/domains.types.ts
- Improve domain service methods documentation
- Add examples to domain service methods
> docs(domains): improve domain service documentation

- docs/api/classes/modules_messaging.MessagingService.md
- docs/api/interfaces/modules_messaging.SubscribeToOptions.md
- docs/api/modules/modules_messaging.md
- src/modules/messaging/messaging.service.ts
- src/modules/messaging/messaging.types.ts
- Improve messaging service methods documentation
- Add examples to messaging service methods
> docs(messaging): improve messaging service documentation

- docs/api/classes/modules_verifiable_credentials.VerifiableCredentialsServiceBase.md
- docs/api/interfaces/modules_verifiable_credentials.InitiateExchangeResults.md
- docs/api/modules/modules_verifiable_credentials.md
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
- Improve VC service methods documentation
- Add examples to VC service methods
> docs(vc): improve verifiable credential service documentation

- docs/api/interfaces/modules_verifiable_credentials.RoleCredentialSubjectParams.md
- e2e/verifiable-credentials.service.e2e.ts
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
Add expiration feature to VC and VP implementation
> feat(vc): add verifiable credential expiration date

- src/modules/cache-client/cache-client.service.ts
> feat: add logs for axios errors

- docs/api/classes/modules_signer.SignerService.md
- src/modules/signer/signer.service.ts
- Improve signer service methods documentation
- Add examples to signer service methods
> docs(signer): improve signer service documentation

- docs/api/classes/modules_signer.SignerService.md
- docs/api/interfaces/modules_cache_client.AuthTokens.md
- docs/api/interfaces/modules_did_registry.GetDIDDocumentOptions.md
- docs/api/interfaces/modules_did_registry.GetDidDelegatesOptions.md
- docs/api/interfaces/modules_did_registry.GetDidPublicKeysOptions.md
- docs/api/interfaces/modules_did_registry.GetServicesOptions.md
- docs/api/modules/modules_cache_client.md
- src/modules/cache-client/cache-client.service.ts
- src/modules/cache-client/cache-client.types.ts
- src/modules/did-registry/did-registry.service.ts
- src/modules/did-registry/did.types.ts
- src/modules/signer/signer.service.ts
Fix previously failed request to SSI-Hub on token refresh.
> fix: retry failed requests on token refresh

- e2e/verifiable-credentials.service.e2e.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
> bug/vp request int't returned

- package-lock.json
- package.json
> merge fix from credentials-governance

- e2e/claim-revocation.e2e.ts
- src/modules/claims/claims.service.ts
Change `namespace` with `claimType`
> fix: on-chain claim revocation

- docs/api/classes/modules_cache_client.CacheClient.md
- docs/api/classes/modules_verifiable_credentials.VerifiableCredentialsServiceBase.md
- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- docs/api/interfaces/modules_claims.IssueVerifiablePresentationOptions.md
- docs/api/interfaces/modules_verifiable_credentials.RoleCredentialSubjectParams.md
- docs/api/modules/modules_verifiable_credentials.md
- src/config/chain.config.ts
Update VOLTA claim registry contract address.
> feat: update claim revocation registry address

- docs/api/README.md
- docs/api/classes/modules_cache_client.CacheClient.md
- docs/api/classes/modules_verifiable_credentials.VerifiableCredentialsServiceBase.md
- docs/api/interfaces/modules_verifiable_credentials.CredentialRevocationDetailsResult.md
- docs/api/interfaces/modules_verifiable_credentials.StatusList2021CredentialSubject.md
- docs/api/interfaces/modules_verifiable_credentials.StatusList2021UnsignedCredential.md
- docs/api/modules/modules_verifiable_credentials.md
- e2e/credential-revocation.e2e.ts
- e2e/fixtures/index.ts
- e2e/fixtures/status-list-credential.ts
- src/modules/cache-client/cache-client.service.ts
- src/modules/claims/claims.service.ts
- src/modules/signer/signer.service.ts
- src/modules/verifiable-credentials/types/index.ts
- src/modules/verifiable-credentials/types/status-list.types.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
- src/modules/verifiable-credentials/verifiable-credentials.const.ts
Add credential revocation feature using StatusList2021.
> feat: add credential revocation

- docs/api/classes/modules_cache_client.CacheClient.md
- docs/api/classes/modules_domains.DomainsService.md
- docs/api/interfaces/modules_cache_client.ICacheClient.md
- package-lock.json
- src/modules/cache-client/cache-client.interface.ts
- src/modules/cache-client/cache-client.service.ts
- src/modules/domains/domains.service.ts
- Add cache client method for https://identitycache-dev.energyweb.org/api/#/Claims/ClaimController_getByAllowedRolesByRevoker
- Add ICL method to retrieve roles by revoker
- Add unit test for ICL method
> #icl 320/get claims by revoker

- src/modules/cache-client/cache-client.service.ts
> fix: cache-client token refresh

- docs/api/interfaces/modules_claims.Claim.md
- src/modules/claims/claims.types.ts
Add missing property to Claim interface.
> feat: add createdAt property to Claim interface

- src/modules/cache-client/cache-client.service.ts
Fix cache client authentication after error occurred
> fix: cache client authentication

- docs/api/classes/modules_domains.DomainsService.md
- docs/api/enums/modules_assets.AssetHistoryEventType.md
- docs/api/enums/modules_cache_client.Order.md
- docs/api/enums/modules_cache_client.SearchType.md
- docs/api/enums/modules_claims.ClaimEventType.md
- docs/api/enums/modules_claims.RegistrationTypes.md
- docs/api/enums/modules_domains.NamespaceType.md
- docs/api/enums/modules_messaging.MessagingMethod.md
- docs/api/enums/modules_signer.ProviderEvent.md
- docs/api/enums/modules_signer.ProviderType.md
- docs/api/enums/modules_staking.StakeStatus.md
- docs/api/interfaces/modules_claims.VerifyEnrolmentPrerequisitesOptions.md
- docs/api/interfaces/modules_domains.SetRoleDefinitionOptions.md
- docs/api/modules/modules_cache_client.md
- docs/api/modules/modules_claims.md
- docs/api/modules/modules_domains.md
- docs/api/modules/modules_messaging.md
- docs/api/modules/modules_signer.md
- docs/api/modules/modules_staking.md
- docs/api/modules/modules_verifiable_credentials.md
- e2e/claims.service.e2e.ts
- package-lock.json
- package.json
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
> feat: use claim default valid period from role definition

- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
> rename issuer credential status

- docs/api/classes/modules_claims.ClaimsService.md
- e2e/claims.service.e2e.ts
- src/modules/claims/claims.service.ts
- Remove unneeded role creation
- Wrap verify tests in describe
- Add test for no resolved credential
> test(verify): Clean up verify tests

- docs/api/classes/modules_claims.ClaimsService.md
- docs/api/interfaces/modules_claims.IssueClaimOptions.md
- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- e2e/auth.e2e.ts
Add more test for authentication
> test: add more test for authentication

- e2e/verifiable-credentials.service.e2e.ts
- src/errors/index.ts
- src/errors/interface-not-satisfied.ts
- src/modules/claims/claims.types.ts
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
> task/ICL-314 can't issue without issuer fields value

- docs/api/interfaces/modules_claims.IssueClaimOptions.md
- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- docs/api/interfaces/modules_claims.IssueVerifiablePresentationOptions.md
- docs/api/interfaces/modules_verifiable_credentials.RoleCredentialSubjectParams.md
- docs/api/modules/modules_verifiable_credentials.md
- package-lock.json
- package.json
> build(dev-deps): update eslint config

- docs/api/classes/modules_claims.ClaimsService.md
- docs/api/classes/modules_verifiable_credentials.VerifiableCredentialsServiceBase.md
- e2e/claims.service.e2e.ts
- package-lock.json
- package.json
- src/errors/error-messages.ts
- src/modules/claims/claims.service.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
- add method to check if given date is expired (used in verifyRoleEIP191JWT and will be used in Switchboard)
- catch 'Credential Expired' error from verifyVC and push to errors array in verifyVc method
- verify that EIP191JWT is not expired in verifyRoleEIP191JWT. Handle expiration error if so
- Add unit tests for expiration resolveCredentialAndVerify, verifyVc and verifyRoleEIP191JWT
> feat(verifyExp): add exp verification method and tests for EIP and VP

- package-lock.json
- package.json
Updates semantic release config in order to add docs and test commit messages in changelog
> update semantic-release config

- docs/api/classes/modules_claims.ClaimsService.md
- src/modules/claims/claims.service.ts
Document ClaimsService.getClaimId method
> Document getClaimId

- src/modules/did-registry/did-registry.validation.ts
> bug/ICL-346 can't add public key to asset document

- package-lock.json
- package.json
> update ew-credentials 2.0.1-alpha.275.0

- README.md
- docs/index.md
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
Adds documentation reference for resolving .wasm file extensions and fallbacks for Node polyfills (webpack). References iam client examples for implementation reference.
> React app build documentation

- docs/api/classes/modules_did_registry.DidRegistry.md
- jest.setup.js
- src/errors/error-messages.ts
- src/modules/claims/claims.service.ts
- src/modules/did-registry/did-registry.service.ts
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
- Use the subject DID to retrieve claimsBySubject (rather than defaulting to signer DID)
> #swtch1425 - use subject DID to for getClaimsBySubject

- e2e/claims.service.e2e.ts
- package-lock.json
- package.json
- src/modules/claims/claims.service.ts
Set RoleEIP191Jwt expiration / `exp` in seconds
> feat: set roleeip191jwt expiration in seconds

- src/modules/claims/claims.service.ts
This PR makes changes to the sequence of verification for a credential. Credential should be verified before issuer verification.
> fix: verify credential before issuer verification

- docs/api/classes/modules_claims.ClaimsService.md
- docs/api/interfaces/modules_claims.CreateClaimRequestOptions.md
- docs/api/interfaces/modules_claims.CreateSelfSignedClaimOptions.md
- docs/api/interfaces/modules_did_registry.ClaimData.md
- docs/api/interfaces/modules_did_registry.CreatePublicClaimOptions.md
- docs/api/modules/modules_did_registry.md
- e2e/cache-client.e2e.ts
- e2e/claims.service.e2e.ts
- package-lock.json
- package.json
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
- src/modules/did-registry/did.types.ts
Merging was preferred over extending in order to not introduce another name and to avoid redefining members
> task/SWTCH-1470 merge ClaimData

- docs/api/classes/modules_claims.ClaimsService.md
- src/modules/claims/claims.service.ts
Adds documentation for registerOnchain to include use case for registering credentials for owned assets. Mentions commit 2c0a860 as it was merged and not included in release due to capitalization error in commit message.
> Commit for2c0a860

- e2e/claims.service.e2e.ts
- src/modules/claims/claims.service.ts
- src/modules/verifiable-credentials/verifiable-credentials-node.service.ts
- src/modules/verifiable-credentials/verifiable-credentials-web.service.ts
1. Removes comment in claims service that was mistakenly merged
2. Applies prettier formatting to files. These files are in need of style formatting but usually have no functional changes and are therefore never added to PRs
> Cleanup: Remove comment and apply formatting

- docs/setup/initialization.md
- src/modules/cache-client/auth.ts
- src/modules/cache-client/cache-client.types.ts
> task/SWTCH-2114 allow different ssi-hub and siwe uri

- .github/renovate.json
> Ignore renovate did-ipfs-store

- .github/workflows/deploy.yml
Fix for https://github.com/energywebfoundation/iam-client-lib/actions/runs/5187529898/jobs/9350003501
> Update node 18

- .github/workflows/deploy.yml
Npm token in semantic-release probably was renamed without mentioning in docs according to this issue https://github.com/semantic-release/semantic-release/issues/2313
> Rename semantic release npm token

- .github/workflows/deploy.yml
- e2e/auth.e2e.ts
- e2e/signer.service.e2e.ts
- e2e/utils/setup-contracts.ts
- jest.config.js
- src/modules/cache-client/cache-client.service.ts
Enable tests, disabled for debugging of publishing
> Enable ci tests

- tsconfig.json
Disable typescript option `suppressImplicitAnyIndexErrors`, because it is going to be deprecated
> Disable suppress any index err

- package-lock.json
- package.json
- src/modules/auth/auth.service.ts
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
- src/utils/logger.ts
`console.log` is noisy: it prints `console.log`, adds line breaks and stack traces. `winston` allows more accurate and manageable logging
> Add Winston logger

- .github/workflows/deploy.yml
Commit type is `fix` in order to trigger release
> Skipping test from `deploy` action
