energywebfoundation/iam-client-lib

- package.json
Previous thresholds of 95% were failing Travis build
> Changing jest coverageThresholds to 0 as there are no tests

- package-lock.json
- package.json
tslib provides runtime helper functions that will be referenced in transpiled code
Needed because the --importHelpers tsconfig flag is used.
Switchboard, for example, has it installed as a dependency: https://github.com/energywebfoundation/switchboard-dapp/blob/62fe762081082064bb6c03069220d98d6f261c03/package.json#L104
> Adding tslib as a dependency

- src/iam.ts
- src/iam/iam-base.ts
- test/application.testSuite.ts
- test/utils/isBrowser.test.ts
iam-client-lib does not allow transferring ownership of the top-level node that you own, because transferring the node requires ownership of the parent node. This PR proposes to remove the parent node ownership restriction
To discuss: these changes allows owner of application not to be owner of app parent organization. Is this consistent with business requirements? Should similar approach be implemented for organization and role transferring?
> [MYEN-515] simplify ownership transfer

- src/iam.ts
BREAKING CHANGE: now isMetamaskExtensionPresent method
returns { isMetamaskPresent: boolean, chainId?: number }
instead of boolean
> feat(metamask): return more info from isMetamaskExtensionPresent

- src/signer/SignerFactory.ts
arrayification is necessary in order for WalletConnect signatures to work. eth_sign expects message in bytes:
https://docs.walletconnect.org/json-rpc-api-methods/ethereum#eth_sign
keccak256 hash is applied in order to obtain message with length of 32 bytes. This allows Metamask to display a coherent hex value when signing.
Tested that WalletConnect and KM sign-in both work 👍
> docs(SignerFactory): add comment re message format

- .releaserc.json
- .travis.yml
According to Semantic-Release npm plugin documentation, there must be an `NPM_TOKEN` environment variable: https://github.com/semantic-release/npm
Was able to successfully publish package with this change:
https://travis-ci.com/github/energywebfoundation/iam-client-lib/jobs/481366487
> Use NPM_TOKEN env var to fix npm publishing

- src/iam/iam-base.ts
Note that this reloads the existing KMS tab (if it exists) and could interrupt the user. Do you think this is a good UX?
> feat(kms integration): reuse existing tab

- src/cacheServerClient/cacheServerClient.ts
- src/errors/ErrorMessages.ts
- src/iam.ts
- src/iam/iam-base.ts
- src/signer/Signer.ts
- src/signer/SignerFactory.ts
- test/application.testSuite.ts
- test/signer/signerFactory.test.ts
This PR contains changes required to move controle of wallet's session to iam-client-lib:
- storing information about current session(publicKey, walletProvider)
- authentication using cookie
- handling networkChange, accountChange and disconnect events
- add static methods to get info about current session
PR needs to merge after [iam-cache-server PR](https://github.com/energywebfoundation/iam-cache-server/pull/65) .
> feat(login): store session information on iam side

- src/iam.ts
- src/iam/iam-base.ts
Our nats exchange server is behind cloudflare, and cloudflare is closing websocket connection after 100 seconds of idleness.
This PR basicly changes the ping interval to 90 seconds to omit closing connection by cloudflare.
> fix(exchange): multiple connections to NATS websocket

- src/GnosisIam.ts
- src/cacheServerClient/cacheServerClient.types.ts
- src/iam.ts
To enable ownership checking in extended version of Iam return type of `getOrgHieararchy` is appended with  `isOwned` property
> include isOwned to org hieararchy

- src/iam.ts
Even if the `deleteClaim` was successful, it was still continuing to throw the error, so just added else block.
> fix(deleteClaim): throw CacheClientNotProvided if necessary

- src/iam/iam-base.ts
- test/claims.testSuite.ts
Adds types for profiles in data claim, because previously it was any.
> Add asset profiles types for claim data.

- src/cacheServerClient/cacheServerClient.types.ts
- src/iam-client-lib.ts
- src/iam.ts
- src/iam/iam-base.ts
Problem is that those interfaces wasn't exported from library. When using nested import in switchboard there was error while building application. This PR should fix it and frontend should be able to use interfaces for ClaimData.
> fix: exporting interfaces for claim data.

- src/cacheServerClient/ICacheServerClient.ts
- src/cacheServerClient/cacheServerClient.ts
- src/iam.ts
- src/iam/iam-base.ts
Fixing a bunch of issues with the login flow:
- fix: login as different account issue
When logout then back in as a separate account was using old cookies.
So check that if publicKey is there so that if not, redo login to cache-server
- fix: maintain login on reload
sessionIsActive() should work even if init() hasn't been called
so moved pubKey retrieval back to constructor
- fix: no sense setting DID if address hasn't been set
So checking this._address when setDid()
- refactor: use isSessionActive() in loginToCacheServer()
Better to have one canonical way to check if session is active
> Swtch 941/logout forbidden

- src/cacheServerClient/ICacheServerClient.ts
- src/iam.ts
Need to migrate legacy definitions if editing or registry will not point to resolver with the latest version
> Swtch 968/redirect legacy definitions

- src/iam.ts
Current code fails eventually in `iam` `private async getClaimId({ claimData }: { claimData: ClaimData }) { ` because `claimData` is null
https://energyweb.atlassian.net/browse/SWTCH-998
> fix(iam): parse claimData from requested token

- package-lock.json
- package.json
- src/iam.ts
- src/iam/iam-base.ts
- src/utils/constants.ts
- src/utils/enrollment.ts
- test/claimsTests/claims.testSuite.ts
- test/claimsTests/enrollmentClaimsTests.ts
- test/claimsTests/selfsignedClaimsTests.ts
- test/iam.test.ts
https://energyweb.atlassian.net/browse/SWTCH-909
`issuer` parameter of `IAM.requestClaimRequest` changed to optional, because at the moment of requesting there are might not be issuers. To persist request it will be published to empty account channel
Had to set ganache network id to 1, because ganache sets its chain id to network id and it breaks tests
> feature/SWTCH-909 issue on-chain role

- bili.config.ts
SWTCH-1055 https://energyweb.atlassian.net/browse/SWTCH-1055, fixes issue #195
rationale: minification is only useful for script-tags/CDN and makes debugging and reading stack trace more difficult
> chore(bili): disable minification of output files

- src/iam.ts
- test/claimsTests/enrollmentClaimsTests.ts
SWTCH-1061
Rename agreement to subjectAgreement in IClaimRequest to align with cache-server
> fix(createClaimRequest): use subjectAgreement

- src/iam.ts
In switchboard when error occurs in metamask while login we get error `[object Object]` like on the screen
This happens when:
1. User cancel operation
2. User have pending interactions.
Fix solves this problem, so in switchboard we will have meaningful messages.
> fix: throwing an error when initializing wallet provider.

- src/iam/iam-base.ts
Method `storeSession` was called before setting `_didSigner` property. This PR solves this problem, we set session storage after setting didSigner.
> fix: setting session in local storage after successful login.

- docs/api/classes/GnosisIam.GnosisIam-1.md
- docs/api/classes/iam.IAM.md
- src/iam.ts
BREAKING CHANGE: Rename the prop name from `issuedToken` to `claimUrl` in method `verifyPublicClaim` in `IAM` class.
> Rename verifyPublicToken param name

- src/iam.ts
- test/assets.testsuite.ts
While offering asset to other user let's use address instead of did format.
> refactor!: drop support for DID format when offering asset. Use address instead

- src/iam.ts
- src/iam/iam-base.ts
- test/claimsTests/enrollmentClaimsTests.ts
- test/testUtils/mocks.ts
fix to make nest.ws module able to found when using the iam-client-lib.esm.js
> fix(nats): changed path to nats.ws from absolute to relative

- docs/api/modules/utils_detectEnvironment.md
- src/utils/detectEnvironment.ts
To use library with newest version of angular and webpack 5 i need to specify global property `(window as any)['global'] = window;`. Because of that, IAM sets `_executionEnvironment` as NODE, which is wrong.
> fix: detecting execution environment, when browser have declared global property.

- docs/api/classes/GnosisIam.GnosisIam-1.md
- docs/api/classes/iam.IAM.md
- docs/api/enums/types_WalletProvider.WalletProvider.md
- src/iam/iam-base.ts
- src/types/WalletProvider.ts
- test/initializeConnection.testSuite.ts
This change allows to use private key to login through frontend application. Current implementation allows to use private key to login only in Node env. This is needed to start e2e testing with private key, to omit metamask login.
> feat/ICL-109: allow to use private key to login in browser env

- .releaserc.json
- semantic release packages order change - npm before git
- add package.json to git assets
> fix(doc): package.json with correct version

- docs/api/classes/modules_signer_signer_service.SignerService.md
- docs/api/enums/modules_signer_signer_types.ProviderEvent.md
- package-lock.json
- src/modules/signer/metamaskSigner.ts
- src/modules/signer/signer.service.ts
- src/modules/signer/signer.types.ts
- src/modules/signer/walletConnectMetamask.ts
I can see two ways to enable signer service to listen on events emitted by `Metamask` or `WalletConnect` wallets:
- Underlying signer can extend `ethers.Signer` with `on` method
- wallet provider notifies signer service
I have chosen second way, because extending signer requires to implement `ethers.Signer` instead of getting it from `Web3Provider` wrapper from `ethers`. May be there is a better design
> bug/SWTCH-1250 Switchboard doesn't relogin on changing Metamask account

- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- docs/api/classes/modules_signer_signer_service.SignerService.md
- e2e/claims.service.e2e.ts
- src/modules/claims/claims.service.ts
- src/modules/signer/signer.service.ts
Implements: https://energyweb.atlassian.net/browse/ICL-159 
@dawidgil should be useful for staking page to check whether or not can try to stake and for seeing whether or not they need to "add" an approve on-chain role to the ClaimManager smart contract (https://energyweb.atlassian.net/browse/SWTCH-1259)
> feat(claims.service): ICL-159 add hasOnChainRole utility

- docs/api/enums/modules_assets_assets_types.AssetHistoryEventType.md
- src/modules/assets/assets.types.ts
asset event type is in use in too many places to perform migration easily
> fix(assets): rollback asset event type to uppercase

- docs/api/classes/modules_cacheClient_cacheClient_service.CacheClient.md
- docs/api/classes/modules_claims_claims_service.ClaimsService.md
- e2e/claims.service.e2e.ts
- e2e/staking.pool.e2e.ts
- e2e/staking.service.e2e.ts
- src/modules/cacheClient/cacheClient.service.ts
- src/modules/claims/claims.service.ts
fields renamed to requestorFields. They will coexist for now for backward compatibility.
> feat(claims): rename fields to requestorFields for better readibility

- e2e/claims.service.e2e.ts
- e2e/staking.pool.e2e.ts
- e2e/staking.service.e2e.ts
- src/errors/ErrorMessages.ts
- src/modules/claims/claims.service.ts
- src/modules/signer/signer.service.ts
- src/modules/signer/signer.types.ts
- src/modules/signer/walletConnectMetamask.ts
https://energyweb.atlassian.net/browse/ICL-171
> bug/ICL-171 onchain claim is not registered by WalletConnect

- docs/api/classes/CacheClient.md
- docs/api/classes/DomainsService.md
- src/modules/cacheClient/cacheClient.service.ts
`getAllowedRolesByIssuer` is currently returning the role definition.
> fix: change return type for `getAllowedRolesByIssuer`

- docs/api/enums/ERROR_MESSAGES.md
- package-lock.json
- package.json
- src/errors/ErrorMessages.ts
- src/modules/didRegistry/didRegistry.service.ts
- src/modules/didRegistry/didRegistry.validation.ts
checking params on updateSignedDidPublicKey, updateSignedDidDelegate functions
checking params on updateDocument conditionally depending on didAttribute value
in case of validation issues - throws Error with the list of invalid or missing properties
- [ v ] Breaking changes - no BC only thing is no more false-positive DID updates. In case there was one, there will be error thrown instead
- [ v ] Documentation - document your code, add comments for method, remember to check if auto generated docs were updated.
- [ v ] Tests - regression tests were used to verify the code
- [ v ] Migration guide - not apply
- [ v ] Configuration correctness - not apply
> feat(did): update did document params validation

- docs/api/classes/ClaimsService.md
- docs/api/interfaces/IClaimIssuance.md
- e2e/claims.service.e2e.ts
- src/init.ts
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
Issue a VC during claim request issuance when `RegistrationTypes` is `OffChain`.
> feat(claim): issue VC when approving role request

- docs/api/classes/modules_assets.AssetsService.md
- src/modules/cache-client/cache-client.service.ts
Avoid refreshing tokens when `refresh token` is undefined
> fix: avoid refreshing undefined token

- e2e/auth.e2e.ts
- package-lock.json
- package.json
- src/modules/cache-client/cache-client.service.ts
> test(cache-client): add authorization tests

- docs/api/classes/modules_claims.ClaimsService.md
- src/modules/verifiable-credentials/verifiable-credentials-base.service.ts
Validate exchange credential types
> refactor: cleanup credential exchange code

- docs/api/interfaces/modules_claims.IssueClaimOptions.md
- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- docs/api/interfaces/modules_claims.IssueVerifiablePresentationOptions.md
- docs/api/interfaces/modules_verifiable_credentials.RoleCredentialSubjectParams.md
- docs/api/modules/modules_verifiable_credentials.md
- src/modules/did-registry/did-registry.service.ts
handle unexpected did service endpoint during fetching claims from DID Document and IPFS
> feat: handle unexpected did service endpoint

- src/modules/cache-client/cache-client.service.ts
This PR adds more details to `[CACHE CLIENT] axios error:` type error log lines. This includes:
* url
* method
* response status code
* response status text
* response headers
* request headers with `Authorization` header value masked
> feat: adding more details to error log line when http request fails

- e2e/signer.service.e2e.ts
- src/modules/signer/signer.service.ts
Add missing set for ethr signer for node clients
> fix: set check ethr signer for node clients

- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
For bug: https://energyweb.atlassian.net/browse/SWTCH-1409
issuerFields can be a boolean value, which is not a valid type in this field check. 
const issuerFields = [{key: 'Checkboolean ', value: true}]
> fix(issue claim): allow boolean as valid field

- docs/api/interfaces/modules_claims.IssueClaimOptions.md
- docs/api/interfaces/modules_claims.IssueClaimRequestOptions.md
- docs/api/interfaces/modules_claims.IssueVerifiablePresentationOptions.md
- docs/api/interfaces/modules_claims.RegisterOnchainOptions.md
- docs/api/interfaces/modules_did_registry.IssuePublicClaimOptions.md
- e2e/claims.service.e2e.ts
- src/modules/claims/claims.types.ts
- src/modules/did-registry/did.types.ts
- src/modules/verifiable-credentials/types/verifiable-credentials.types.ts
Updates documentation for expirationTimestamp to be explicit that the timestamp is in milliseconds
> fix(exp): document expirationTimestamp

- package-lock.json
- package.json
- Bumps ew-credentials version. If a user has a request to approve a role that she does not have the correct approval role for, the error will specify the role that she does not have. 
- Old Error: No authorative credential found for issuer
- New Error: No authorative credential found for issuer for role "installer.role..."
@jrhender and @JGiter It sounded from the [story](https://energyweb.atlassian.net/jira/software/projects/SWTCH/boards/54?assignee=608057a2e3b59800688dbc2a&selectedIssue=SWTCH-1455) that you wanted to add more info to this error. Should ICL catch the error from verifyIssuer, and if the error contains this text return it with more descriptive error message such as 'No authorative credential found for issuer for role "installer.role...". You must obtain and publish this …
> fix: bump ew-credentials to 2.2.1-alpha.296.0

- docs/api/interfaces/modules_assets.AssetHistory.md
- src/modules/assets/assets.types.ts
Add `type` property missing in `AssetHistory`, this would make it consistent with the `AssetHistory` entity in `SSI-Hub` - https://github.com/energywebfoundation/ssi-hub/blob/9e653eeb14f1b0ce8d63a1c50a90eea548294ca7/src/modules/assets/assets.entity.ts#L76
> fix: add type attribute in assethistory

- package-lock.json
- package.json
Updates ew-credentials packages to 2.2.1-alpha.312 . Needed to have `schema` prop available in `FieldDefinition`.
I didn't add a test for `schema` functionality as we don't have test coverage yet for different `FieldDefinitions` as far as I can tell
Relates to https://github.com/energywebfoundation/ssi-hub/pull/554
> chore: update ew-creds packages to 2.2.1-alpha.312

- README.md
- docs/index.md
> docs(README): update team members and install instructions

- src/modules/cache-client/auth.ts
Fixes missing `/v1` in default Siwe uri
> bug: missing /v1 in Siwe uri

- .github/workflows/deploy.yml
semantic release action https://github.com/codfish/semantic-release-action uses outdated version of semantic release. May be this is reason of failing builds. Trying to fix this by configuring workflow according with semanti-release docs https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions, which doesn't require additional github actions
Temporarily turned off tests, because they take too long
> Remove semantic release action

- src/modules/signer/wallet-connect-metamask.ts
This is fix for `TypeError: Class extends value #<Object> is not a constructor or null` in gp4btc
> Delete metamask connector

- docs/api/classes/modules_signer.SignerService.md
- docs/api/classes/modules_staking.StakingFactoryService.md
- docs/api/classes/modules_staking.StakingPoolService.md
- docs/api/classes/modules_verifiable_credentials.VerifiableCredentialsServiceBase.md
- docs/api/interfaces/modules_claims.Claim.md
- docs/api/modules/modules_signer.md
- src/modules/claims/claims.service.ts
- src/modules/claims/claims.types.ts
Claim expiration timestamp is defined as string though in fact it is number https://github.com/energywebfoundation/ssi-hub/blob/291ab134d182a9fb658fbe56d469172f23840711/src/modules/claim/entities/roleClaim.entity.ts#L101
This fix is not a breaking change, because `expirationTimestamp` anyways converted to number in the only place where it is used https://github.com/energywebfoundation/iam-client-lib/blob/6db25b741f79ba642688a39180afcdf86b071e8c/src/modules/claims/claims.service.ts#L796
> Fix claim expiration timestamp

- src/modules/claims/claims.service.ts
Checks issuer verification result
> bug/swtch-3035 Not valid VC are verified
